/bin/aa-enabled
/bin/aa-exec
/bin/aa-features-abi
/bin/aconnect
/bin/acyclic
/bin/addpart
/bin/airscan-discover
/bin/alsabat
/bin/alsaloop
/bin/alsamixer
/bin/alsatplg
/bin/alsaucm
/bin/amidi
/bin/amixer
/bin/apgbfm
/bin/aplay
/bin/aplaymidi
/bin/appres
/bin/appstreamcli
/bin/apt
/bin/apt-cache
/bin/apt-cdrom
/bin/apt-config
/bin/apt-extracttemplates
/bin/apt-ftparchive
/bin/apt-get
/bin/apt-mark
/bin/apt-sortpkgs
/bin/arch
/bin/arecordmidi
/bin/aria_chk
/bin/aria_dump_log
/bin/aria_ftdump
/bin/aria_pack
/bin/aria_read_log
/bin/as31
/bin/aseqdump
/bin/aseqnet
/bin/aspell
/bin/at
/bin/atobm
/bin/autogen
/bin/avahi-browse
/bin/avahi-publish
/bin/avahi-resolve
/bin/avahi-set-host-name
/bin/avinfo
/bin/axfer
/bin/b2sum
/bin/baobab
/bin/base32
/bin/base64
/bin/basename
/bin/basenc
/bin/bash
/bin/bc
/bin/bcomps
/bin/bdftopcf
/bin/bdftruncate
/bin/bison
/bin/bluemoon
/bin/bluetoothctl
/bin/bluetooth-sendto
/bin/bmtoa
/bin/boltctl
/bin/bootctl
/bin/broadwayd
/bin/btattach
/bin/btmgmt
/bin/btmon
/bin/btrfs
/bin/btrfs-convert
/bin/btrfs-find-root
/bin/btrfs-image
/bin/btrfs-map-logical
/bin/btrfs-select-super
/bin/btrfstune
/bin/bunzip2
/bin/busctl
/bin/busybox
/bin/bwrap
/bin/bzcat
/bin/bzip2
/bin/bzip2recover
/bin/canberra-gtk-play
/bin/cancel
/bin/capinfos
/bin/captype
/bin/cargo
/bin/cat
/bin/catman
/bin/ccomps
/bin/cct
/bin/cd-create-profile
/bin/cd-fix-profile
/bin/cd-iccdump
/bin/cd-it8
/bin/cgi-fcgi
/bin/cg_merge
/bin/chacl
/bin/chage
/bin/chattr
/bin/chcon
/bin/cheese
/bin/chfn
/bin/chg
/bin/chgrp
/bin/chmod
/bin/choom
/bin/chown
/bin/chronyc
/bin/chrt
/bin/chsh
/bin/chvt
/bin/ciptool
/bin/cksum
/bin/clear
/bin/clear_console
/bin/cluster
/bin/cmake
/bin/cmp
/bin/codepage
/bin/col
/bin/colcrt
/bin/colormgr
/bin/colrm
/bin/column
/bin/columns
/bin/comm
/bin/containerd
/bin/containerd-shim-runc-v2
/bin/cp
/bin/cpack
/bin/cpio
/bin/cppcheck
/bin/crontab
/bin/cs2cs
/bin/csplit
/bin/ctags.emacs
/bin/ctest
/bin/ctr
/bin/cupstestppd
/bin/curl
/bin/cut
/bin/cvt
/bin/cvtsudoers
/bin/darcs
/bin/dash
/bin/date
/bin/dbus-cleanup-sockets
/bin/dbus-daemon
/bin/dbus-monitor
/bin/dbus-run-session
/bin/dbus-send
/bin/dbus-update-activation-environment
/bin/dbus-uuidgen
/bin/dbxtool
/bin/dconf
/bin/dd
/bin/deallocvt
/bin/debian-distro-info
/bin/delaunay
/bin/delpart
/bin/delv
/bin/derb
/bin/desktop-file-install
/bin/desktop-file-validate
/bin/df
/bin/dfu-tool
/bin/diff
/bin/diff3
/bin/diffimg
/bin/dig
/bin/dijkstra
/bin/dir
/bin/dircolors
/bin/dirmngr
/bin/dirmngr-client
/bin/dirname
/bin/dmesg
/bin/dm-tool
/bin/docker
/bin/dockerd
/bin/docker-proxy
/bin/dot_builtins
/bin/dpkg
/bin/dpkg-deb
/bin/dpkg-divert
/bin/dpkg-query
/bin/dpkg-split
/bin/dpkg-statoverride
/bin/dpkg-trigger
/bin/du
/bin/dumpcap
/bin/dumpkeys
/bin/dumpsexp
/bin/ebrowse.emacs
/bin/echo
/bin/ed
/bin/edgepaint
/bin/editcap
/bin/editres
/bin/efibootdump
/bin/efibootmgr
/bin/eject
/bin/emacsclient.emacs
/bin/emacs-gtk
/bin/enchant-2
/bin/enchant-lsmod-2
/bin/env
/bin/envsubst
/bin/eog
/bin/eqn
/bin/errno
/bin/etags.emacs
/bin/evince
/bin/evince-previewer
/bin/evince-thumbnailer
/bin/expand
/bin/expiry
/bin/expr
/bin/factor
/bin/faillog
/bin/faked-sysv
/bin/faked-tcp
/bin/fallocate
/bin/false
/bin/fbstat
/bin/fbsvcmgr
/bin/fc-cache
/bin/fc-cat
/bin/fc-conflist
/bin/fc-list
/bin/fc-match
/bin/fc-pattern
/bin/fc-query
/bin/fc-scan
/bin/fc-validate
/bin/fgconsole
/bin/filan
/bin/file
/bin/file2brl
/bin/file-roller
/bin/fincore
/bin/find
/bin/findmnt
/bin/fish
/bin/fish_indent
/bin/fish_key_reader
/bin/flex
/bin/flock
/bin/fmt
/bin/fold
/bin/fonttosfnt
/bin/free
/bin/funzip
/bin/fuser
/bin/fusermount3
/bin/fwupdate
/bin/fwupdmgr
/bin/fwupdtool
/bin/gamma4scanimage
/bin/gapplication
/bin/gatttool
/bin/gawk
/bin/gbak
/bin/gc
/bin/gcalccmd
/bin/gcr-viewer
/bin/gdb
/bin/gdbus
/bin/gdk-pixbuf-csource
/bin/gdk-pixbuf-pixdata
/bin/gdk-pixbuf-thumbnailer
/bin/gdmflexiserver
/bin/gedit
/bin/genbrk
/bin/gencat
/bin/gencfu
/bin/gencnval
/bin/gendict
/bin/genrb
/bin/geod
/bin/getconf
/bin/getdefs
/bin/getent
/bin/getfacl
/bin/getkeycodes
/bin/getopt
/bin/gettext
/bin/gfix
/bin/gie
/bin/gimp-2.10
/bin/gimp-console-2.10
/bin/gimp-test-clipboard-2.0
/bin/gio
/bin/g-ir-compiler
/bin/g-ir-generate
/bin/g-ir-inspect
/bin/git
/bin/git-lfs
/bin/git-shell
/bin/gjs-console
/bin/gkbd-keyboard-display
/bin/glewinfo
/bin/glib-compile-resources
/bin/glmark2
/bin/gml2gv
/bin/gnome-calculator
/bin/gnome-calendar
/bin/gnome-contacts
/bin/gnome-control-center
/bin/gnome-disk-image-mounter
/bin/gnome-disks
/bin/gnome-extensions
/bin/gnome-font-viewer
/bin/gnome-keyring-3
/bin/gnome-keyring-daemon
/bin/gnome-logs
/bin/gnome-power-statistics
/bin/gnome-screensaver
/bin/gnome-screensaver-command
/bin/gnome-session-inhibit
/bin/gnome-session-properties
/bin/gnome-session-quit
/bin/gnome-shell
/bin/gnome-system-monitor
/bin/gnome-terminal.real
/bin/gnome-thumbnail-font
/bin/gnome-todo
/bin/gobject-query
/bin/gpasswd
/bin/gpg
/bin/gpg-agent
/bin/gpgcompose
/bin/gpgconf
/bin/gpg-connect-agent
/bin/gpgparsemail
/bin/gpgsm
/bin/gpgsplit
/bin/gpgtar
/bin/gpgv
/bin/gpg-wks-server
/bin/gpre
/bin/gpu-manager
/bin/graphml2gv
/bin/grdctl
/bin/grep
/bin/gresource
/bin/groff
/bin/grops
/bin/grotty
/bin/groups
/bin/grub-editenv
/bin/grub-file
/bin/grub-fstest
/bin/grub-glue-efi
/bin/grub-menulst2cfg
/bin/grub-mkfont
/bin/grub-mkimage
/bin/grub-mklayout
/bin/grub-mknetdir
/bin/grub-mkpasswd-pbkdf2
/bin/grub-mkrelpath
/bin/grub-mkrescue
/bin/grub-mkstandalone
/bin/grub-mount
/bin/grub-render-label
/bin/grub-script-check
/bin/grub-syslinux2cfg
/bin/gs
/bin/gsec
/bin/gsettings
/bin/gst-device-monitor-1.0
/bin/gst-discoverer-1.0
/bin/gst-inspect-1.0
/bin/gst-launch-1.0
/bin/gst-play-1.0
/bin/gst-stats-1.0
/bin/gst-tester-1.0
/bin/gst-typefind-1.0
/bin/gtester
/bin/gtf
/bin/gtk4-builder-tool
/bin/gtk4-encode-symbolic-svg
/bin/gtk4-launch
/bin/gtk4-query-settings
/bin/gtk4-update-icon-cache
/bin/gtk-builder-tool
/bin/gtk-encode-symbolic-svg
/bin/gtk-launch
/bin/gtk-query-settings
/bin/gtk-update-icon-cache
/bin/gts2dxf
/bin/gts2oogl
/bin/gts2stl
/bin/gts2xyz
/bin/gtscheck
/bin/gtscompare
/bin/gv2gml
/bin/gvcolor
/bin/gvgen
/bin/gvmap
/bin/gvpack
/bin/gvpr
/bin/gxl2gv
/bin/gzip
/bin/hardlink
/bin/hciattach
/bin/hciconfig
/bin/hcitool
/bin/head
/bin/hex2hcd
/bin/hexchat
/bin/hexdump
/bin/hmac256
/bin/host
/bin/hostid
/bin/hostname
/bin/hostnamectl
/bin/htop
/bin/ibus
/bin/ibus-daemon
/bin/iceauth
/bin/ico
/bin/iconv
/bin/icuexportdata
/bin/icuinfo
/bin/id
/bin/iecset
/bin/ifdata
/bin/ifne
/bin/info
/bin/infocmp
/bin/innochecksum
/bin/inputattach
/bin/install
/bin/install-info
/bin/intel-virtual-output
/bin/ionice
/bin/ip
/bin/ipcmk
/bin/ipcrm
/bin/ipcs
/bin/ippfind
/bin/ipptool
/bin/ischroot
/bin/isdv4-serial-debugger
/bin/isdv4-serial-inputattach
/bin/isql-fb
/bin/isutf8
/bin/join
/bin/journalctl
/bin/jq
/bin/k5start
/bin/kadmin
/bin/kbdinfo
/bin/kbd_mode
/bin/kbuildsycoca5
/bin/kbxutil
/bin/kcachegrind
/bin/kcookiejar5
/bin/kded5
/bin/kde-geo-uri-handler
/bin/kdestroy
/bin/keyctl
/bin/kglobalaccel5
/bin/kiconfinder5
/bin/kill
/bin/killall
/bin/kinit
/bin/klist
/bin/kmod
/bin/kmodsign
/bin/kpasswd
/bin/kquitapp5
/bin/kreadconfig5
/bin/krenew
/bin/ksu
/bin/kswitch
/bin/ktelnetservice5
/bin/ktrash5
/bin/ktutil
/bin/kvno
/bin/kwalletd5
/bin/kwallet-query
/bin/kwriteconfig5
/bin/l2ping
/bin/l2test
/bin/last
/bin/lastlog
/bin/lckdo
/bin/ldapcompare
/bin/ldapdelete
/bin/ldapexop
/bin/ldapmodify
/bin/ldapmodrdn
/bin/ldappasswd
/bin/ldapsearch
/bin/ldapurl
/bin/ldapwhoami
/bin/ldrdf
/bin/lefty
/bin/less
/bin/lessecho
/bin/lesskey
/bin/lexgrog
/bin/libwacom-list-devices
/bin/libwacom-list-local-devices
/bin/link
/bin/listres
/bin/ln
/bin/lnstat
/bin/loadkeys
/bin/loadunimap
/bin/locale
/bin/locale-check
/bin/localectl
/bin/localedef
/bin/logger
/bin/login
/bin/loginctl
/bin/logname
/bin/look
/bin/lowntfs-3g
/bin/lp
/bin/lpoptions
/bin/lp_solve
/bin/lpstat
/bin/ls
/bin/lsattr
/bin/lsblk
/bin/lscpu
/bin/lshw
/bin/lsipc
/bin/lslocks
/bin/lslogins
/bin/lsmem
/bin/lsns
/bin/lsof
/bin/lspci
/bin/lsusb
/bin/lua5.4
/bin/luac5.4
/bin/luit
/bin/lzmainfo
/bin/m4
/bin/machinectl
/bin/make
/bin/makeconv
/bin/man
/bin/mandb
/bin/manpath
/bin/man-recode
/bin/mapscrn
/bin/mariadb
/bin/mariadb-admin
/bin/mariadb-binlog
/bin/mariadb-check
/bin/mariadb-conv
/bin/mariadbd-safe-helper
/bin/mariadb-dump
/bin/mariadb-import
/bin/mariadb-plugin
/bin/mariadb-show
/bin/mariadb-slap
/bin/mariadb-tzinfo-to-sql
/bin/mariadb-upgrade
/bin/mariadb-waitpid
/bin/mawk
/bin/mcookie
/bin/md5sum
/bin/mdig
/bin/memusagestat
/bin/mergecap
/bin/mesg
/bin/mingle
/bin/mispipe
/bin/mkdir
/bin/mkfifo
/bin/mkfontscale
/bin/mknod
/bin/mksquashfs
/bin/mktemp
/bin/mm2gv
/bin/mmcli
/bin/mmdbresolve
/bin/mokutil
/bin/monitor-sensor
/bin/more
/bin/mount
/bin/mountpoint
/bin/mpicalc
/bin/mt-gnu
/bin/mtr
/bin/mtr-packet
/bin/mv
/bin/myisamchk
/bin/myisam_ftdump
/bin/myisamlog
/bin/myisampack
/bin/my_print_defaults
/bin/namei
/bin/nano
/bin/nasm
/bin/nautilus
/bin/nautilus-autorun-software
/bin/nautilus-sendto
/bin/nbackup
/bin/ncdu
/bin/nc.openbsd
/bin/ndisasm
/bin/netstat
/bin/networkctl
/bin/newgidmap
/bin/newgrp
/bin/newuidmap
/bin/ngettext
/bin/nice
/bin/nl
/bin/nm-applet
/bin/nmcli
/bin/nm-connection-editor
/bin/nm-online
/bin/nmtui
/bin/node
/bin/nohup
/bin/nop
/bin/notify-send
/bin/nproc
/bin/nsenter
/bin/nslookup
/bin/nstat
/bin/nsupdate
/bin/ntfs-3g
/bin/ntfs-3g.probe
/bin/ntfscat
/bin/ntfscluster
/bin/ntfscmp
/bin/ntfsdecrypt
/bin/ntfsfallocate
/bin/ntfsfix
/bin/ntfsinfo
/bin/ntfsls
/bin/ntfsmove
/bin/ntfsrecover
/bin/ntfssecaudit
/bin/ntfstruncate
/bin/ntfsusermap
/bin/ntfswipe
/bin/numfmt
/bin/numlockx
/bin/nvim
/bin/obexctl
/bin/ocamlcmt
/bin/ocamlc.opt
/bin/ocamlcp.opt
/bin/ocamldep.opt
/bin/ocamldoc.opt
/bin/ocamllex.opt
/bin/ocamlmklib.opt
/bin/ocamlmktop.opt
/bin/ocamlobjinfo.opt
/bin/ocamlopt.opt
/bin/ocamloptp.opt
/bin/ocamlprof.opt
/bin/ocamlrun
/bin/ocamlrund
/bin/ocamlruni
/bin/ocamlyacc
/bin/oclock
/bin/od
/bin/ollama
/bin/opam
/bin/opam-installer
/bin/openssl
/bin/openvt
/bin/p11-kit
/bin/pacat
/bin/pacmd
/bin/pactl
/bin/pango-list
/bin/pango-segmentation
/bin/pango-view
/bin/paperconf
/bin/parallel
/bin/partx
/bin/passwd
/bin/paste
/bin/pasuspender
/bin/patch
/bin/pathchk
/bin/pax11publish
/bin/pdfattach
/bin/pdfdetach
/bin/pdffonts
/bin/pdfimages
/bin/pdfinfo
/bin/pdfseparate
/bin/pdfsig
/bin/pdftocairo
/bin/pdftohtml
/bin/pdftoppm
/bin/pdftops
/bin/pdftotext
/bin/pdfunite
/bin/pee
/bin/peekfd
/bin/perl
/bin/perl5.34.0
/bin/perl5.34-x86_64-linux-gnu
/bin/perror
/bin/pgrep
/bin/php8.1
/bin/pic
/bin/pidwait
/bin/pigz
/bin/pinentry-curses
/bin/pinentry-gnome3
/bin/ping
/bin/pinky
/bin/pipewire
/bin/pipewire-media-session
/bin/pkaction
/bin/pkcheck
/bin/pkexec
/bin/pkg-config
/bin/pkgdata
/bin/pkttyagent
/bin/pldd
/bin/plymouth
/bin/pmap
/bin/pngfix
/bin/png-fix-itxt
/bin/portablectl
/bin/ppdc
/bin/ppdhtml
/bin/ppdi
/bin/ppdmerge
/bin/ppdpo
/bin/pr
/bin/preconv
/bin/prezip-bin
/bin/printenv
/bin/printf
/bin/prlimit
/bin/procan
/bin/proj
/bin/projinfo
/bin/projsync
/bin/prometheus-node-exporter
/bin/protocoltojson
/bin/proxy
/bin/prtstat
/bin/prune
/bin/ps
/bin/psfxtable
/bin/pslog
/bin/pstree
/bin/ptx
/bin/pulseaudio
/bin/pw-cat
/bin/pw-cli
/bin/pwd
/bin/pw-dot
/bin/pw-dump
/bin/pwdx
/bin/pw-link
/bin/pw-loopback
/bin/pw-metadata
/bin/pw-mididump
/bin/pw-mon
/bin/pw-profiler
/bin/pw-reserve
/bin/pw-top
/bin/python3.10
/bin/python3.7
/bin/python3.7m
/bin/pzstd
/bin/qemu-img
/bin/qemu-io
/bin/qemu-nbd
/bin/qemu-pr-helper
/bin/qemu-storage-daemon
/bin/qemu-system-aarch64
/bin/qemu-system-alpha
/bin/qemu-system-arm
/bin/qemu-system-avr
/bin/qemu-system-cris
/bin/qemu-system-hppa
/bin/qemu-system-i386
/bin/qemu-system-m68k
/bin/qemu-system-microblaze
/bin/qemu-system-microblazeel
/bin/qemu-system-mips
/bin/qemu-system-mips64
/bin/qemu-system-mips64el
/bin/qemu-system-mipsel
/bin/qemu-system-nios2
/bin/qemu-system-or1k
/bin/qemu-system-ppc
/bin/qemu-system-ppc64
/bin/qemu-system-riscv32
/bin/qemu-system-riscv64
/bin/qemu-system-rx
/bin/qemu-system-s390x
/bin/qemu-system-sh4
/bin/qemu-system-sh4eb
/bin/qemu-system-sparc
/bin/qemu-system-sparc64
/bin/qemu-system-tricore
/bin/qemu-system-x86_64
/bin/qemu-system-x86_64-microvm
/bin/qemu-system-xtensa
/bin/qemu-system-xtensaeb
/bin/qtchooser
/bin/qtcreator
/bin/quota
/bin/quotasync
/bin/randpkt
/bin/rawshark
/bin/rctest
/bin/rdf2bin
/bin/rdfdump
/bin/rdflib
/bin/rdma
/bin/rdx
/bin/readlink
/bin/realpath
/bin/redis-benchmark
/bin/redis-check-aof
/bin/redis-check-rdb
/bin/redis-cli
/bin/remmina
/bin/remote-viewer
/bin/rendercheck
/bin/renice
/bin/reordercap
/bin/replace
/bin/resize
/bin/resizecons
/bin/resizepart
/bin/resolvectl
/bin/resolveip
/bin/resolve_stack_dump
/bin/rev
/bin/rfcomm
/bin/rg
/bin/rm
/bin/rmdir
/bin/rootlesskit
/bin/rpcgen
/bin/rpcinfo
/bin/rsync
/bin/ruby3.0
/bin/runc
/bin/runcon
/bin/run-parts
/bin/rustc
/bin/rustdoc
/bin/rygel
/bin/sane-find-scanner
/bin/sbattach
/bin/sbkeysync
/bin/sbsiglist
/bin/sbsign
/bin/sbvarsign
/bin/sbverify
/bin/scanimage
/bin/sccmap
/bin/scp
/bin/screen
/bin/screendump
/bin/script
/bin/scriptlive
/bin/scriptreplay
/bin/sdiff
/bin/sdptool
/bin/sed
/bin/seq
/bin/session-migration
/bin/sessreg
/bin/setarch
/bin/setfacl
/bin/setfont
/bin/setkeycodes
/bin/setleds
/bin/setlogcons
/bin/setmetamode
/bin/setpci
/bin/setpriv
/bin/setsid
/bin/setterm
/bin/setxkbmap
/bin/sftp
/bin/sg_bg_ctl
/bin/sg_compare_and_write
/bin/sg_copy_results
/bin/sg_dd
/bin/sg_decode_sense
/bin/sg_emc_trespass
/bin/sg_format
/bin/sg_get_config
/bin/sg_get_elem_status
/bin/sg_get_lba_status
/bin/sg_ident
/bin/sginfo
/bin/sg_inq
/bin/sg_logs
/bin/sg_luns
/bin/sg_map
/bin/sg_map26
/bin/sgm_dd
/bin/sg_modes
/bin/sg_opcodes
/bin/sgp_dd
/bin/sg_persist
/bin/sg_prevent
/bin/sg_raw
/bin/sg_rbuf
/bin/sg_rdac
/bin/sg_read
/bin/sg_read_attr
/bin/sg_read_block_limits
/bin/sg_read_buffer
/bin/sg_readcap
/bin/sg_read_long
/bin/sg_reassign
/bin/sg_referrals
/bin/sg_rep_pip
/bin/sg_rep_zones
/bin/sg_requests
/bin/sg_reset
/bin/sg_reset_wp
/bin/sg_rmsn
/bin/sg_rtpg
/bin/sg_safte
/bin/sg_sanitize
/bin/sg_sat_identify
/bin/sg_sat_phy_event
/bin/sg_sat_read_gplog
/bin/sg_sat_set_features
/bin/sg_scan
/bin/sg_seek
/bin/sg_senddiag
/bin/sg_ses
/bin/sg_ses_microcode
/bin/sg_start
/bin/sg_stpg
/bin/sg_stream_ctl
/bin/sg_sync
/bin/sg_test_rwbuf
/bin/sg_timestamp
/bin/sg_turs
/bin/sg_unmap
/bin/sg_verify
/bin/sg_vpd
/bin/sg_write_buffer
/bin/sg_write_long
/bin/sg_write_same
/bin/sg_write_verify
/bin/sg_write_x
/bin/sg_wr_mode
/bin/sg_xcopy
/bin/sg_zone
/bin/sha1sum
/bin/sha224sum
/bin/sha256sum
/bin/sha384sum
/bin/sha512sum
/bin/sharkd
/bin/showconsolefont
/bin/showkey
/bin/showrgb
/bin/shred
/bin/shuf
/bin/siege
/bin/simplescreenrecorder
/bin/skill
/bin/slabtop
/bin/sleep
/bin/slirp4netns
/bin/smproxy
/bin/snap
/bin/snapfuse
/bin/socat
/bin/soelim
/bin/sort
/bin/spa-acp-tool
/bin/spa-inspect
/bin/spa-json-dump
/bin/spa-monitor
/bin/spa-resample
/bin/spd-say
/bin/spdsend
/bin/speaker-test
/bin/speech-dispatcher
/bin/spice-vdagent
/bin/split
/bin/splitfont
/bin/sponge
/bin/sprof
/bin/sqlite3
/bin/ss
/bin/ssh
/bin/ssh-add
/bin/ssh-agent
/bin/ssh-keygen
/bin/ssh-keyscan
/bin/sss_ssh_authorizedkeys
/bin/sss_ssh_knownhostsproxy
/bin/stat
/bin/stdbuf
/bin/stl2gts
/bin/strace
/bin/stty
/bin/su
/bin/sudoreplay
/bin/sum
/bin/swtpm
/bin/swtpm_bios
/bin/swtpm_cert
/bin/swtpm_ioctl
/bin/swtpm_setup
/bin/sync
/bin/systemctl
/bin/systemd-analyze
/bin/systemd-ask-password
/bin/systemd-cat
/bin/systemd-cgls
/bin/systemd-cgtop
/bin/systemd-cryptenroll
/bin/systemd-delta
/bin/systemd-detect-virt
/bin/systemd-dissect
/bin/systemd-escape
/bin/systemd-hwdb
/bin/systemd-id128
/bin/systemd-inhibit
/bin/systemd-machine-id-setup
/bin/systemd-mount
/bin/systemd-notify
/bin/systemd-nspawn
/bin/systemd-path
/bin/systemd-run
/bin/systemd-socket-activate
/bin/systemd-stdio-bridge
/bin/systemd-sysext
/bin/systemd-sysusers
/bin/systemd-tmpfiles
/bin/systemd-tty-ask-password-agent
/bin/tabs
/bin/tac
/bin/tail
/bin/tar
/bin/taskset
/bin/tbl
/bin/tclsh8.6
/bin/tcpdump
/bin/tee
/bin/telnet.netkit
/bin/tempfile
/bin/test
/bin/text2pcap
/bin/tic
/bin/time
/bin/timedatectl
/bin/timeout
/bin/tload
/bin/tmux
/bin/tnftp
/bin/toe
/bin/top
/bin/totem
/bin/totem-video-thumbnailer
/bin/touch
/bin/tput
/bin/tr
/bin/tracepath
/bin/tracker3
/bin/transform
/bin/transset
/bin/tred
/bin/tree
/bin/troff
/bin/true
/bin/truncate
/bin/trust
/bin/tset
/bin/tsort
/bin/tty
/bin/ubuntu-distro-info
/bin/ubuntu-report
/bin/uclampset
/bin/uconv
/bin/ucs2any
/bin/udevadm
/bin/udisksctl
/bin/ul
/bin/umax_pp
/bin/umount
/bin/uname
/bin/unexpand
/bin/unflatten
/bin/uniq
/bin/unity-scope-loader
/bin/unlink
/bin/unpigz
/bin/unshare
/bin/unsquashfs
/bin/unzip
/bin/unzipsfx
/bin/update-alternatives
/bin/update-desktop-database
/bin/update-mime-database
/bin/upower
/bin/uptime
/bin/usbhid-dump
/bin/usbreset
/bin/users
/bin/utmpdump
/bin/uuidgen
/bin/uuidparse
/bin/valgrind.bin
/bin/valgrind-di-server
/bin/valgrind-listener
/bin/VBoxDTrace
/bin/vdir
/bin/VGAuthService
/bin/vgdb
/bin/viewres
/bin/vim.basic
/bin/vim.tiny
/bin/virsh
/bin/virt-admin
/bin/virt-host-validate
/bin/virt-pki-query-dn
/bin/virt-qemu-run
/bin/virt-ssh-helper
/bin/virt-viewer
/bin/visualinfo
/bin/vkcube
/bin/vkcubepp
/bin/vlc
/bin/vlc-wrapper
/bin/vmhgfs-fuse
/bin/vmstat
/bin/vmtoolsd
/bin/vmware-alias-import
/bin/vmware-checkvm
/bin/vmwarectrl
/bin/vmware-hgfsclient
/bin/vmware-namespace-cmd
/bin/vmware-rpctool
/bin/vmware-toolbox-cmd
/bin/vmware-vgauth-cmd
/bin/vmware-vmblock-fuse
/bin/vmware-xferlogs
/bin/vulkaninfo
/bin/w
/bin/wall
/bin/watch
/bin/watchgnupg
/bin/wayland-scanner
/bin/wc
/bin/wdctl
/bin/weechat
/bin/wget
/bin/whatis
/bin/whereis
/bin/whiptail
/bin/who
/bin/whoami
/bin/whoopsie
/bin/whoopsie-preferences
/bin/wireshark
/bin/wish8.6
/bin/word-list-compress
/bin/wpa_passphrase
/bin/write.ul
/bin/x11perf
/bin/x11vnc
/bin/x86_64-linux-gnu-addr2line
/bin/x86_64-linux-gnu-ar
/bin/x86_64-linux-gnu-as
/bin/x86_64-linux-gnu-c++filt
/bin/x86_64-linux-gnu-cpp-11
/bin/x86_64-linux-gnu-cpp-12
/bin/x86_64-linux-gnu-dwp
/bin/x86_64-linux-gnu-elfedit
/bin/x86_64-linux-gnu-g++-11
/bin/x86_64-linux-gnu-g++-12
/bin/x86_64-linux-gnu-gcc-11
/bin/x86_64-linux-gnu-gcc-12
/bin/x86_64-linux-gnu-gcc-ar-11
/bin/x86_64-linux-gnu-gcc-ar-12
/bin/x86_64-linux-gnu-gcc-nm-11
/bin/x86_64-linux-gnu-gcc-nm-12
/bin/x86_64-linux-gnu-gcc-ranlib-11
/bin/x86_64-linux-gnu-gcc-ranlib-12
/bin/x86_64-linux-gnu-gcov-11
/bin/x86_64-linux-gnu-gcov-12
/bin/x86_64-linux-gnu-gcov-dump-11
/bin/x86_64-linux-gnu-gcov-dump-12
/bin/x86_64-linux-gnu-gcov-tool-11
/bin/x86_64-linux-gnu-gcov-tool-12
/bin/x86_64-linux-gnu-gprof
/bin/x86_64-linux-gnu-ld.bfd
/bin/x86_64-linux-gnu-ld.gold
/bin/x86_64-linux-gnu-lto-dump-11
/bin/x86_64-linux-gnu-lto-dump-12
/bin/x86_64-linux-gnu-nm
/bin/x86_64-linux-gnu-objcopy
/bin/x86_64-linux-gnu-objdump
/bin/x86_64-linux-gnu-ranlib
/bin/x86_64-linux-gnu-readelf
/bin/x86_64-linux-gnu-size
/bin/x86_64-linux-gnu-strings
/bin/x86_64-linux-gnu-strip
/bin/x86_64-pc-linux-gnu-pkg-config
/bin/xargs
/bin/xauth
/bin/xbiff
/bin/xbrlapi
/bin/xcalc
/bin/xclip
/bin/xclipboard
/bin/xclock
/bin/xcmsdb
/bin/xconsole
/bin/xcursorgen
/bin/xcutsel
/bin/xdg-dbus-proxy
/bin/xdg-user-dirs-gtk-update
/bin/xdg-user-dirs-update
/bin/xditview
/bin/xdpyinfo
/bin/xdriinfo
/bin/xedit
/bin/Xephyr
/bin/xev
/bin/xeyes
/bin/xfd
/bin/xfontsel
/bin/xgamma
/bin/xgc
/bin/xhost
/bin/xinit
/bin/xinput
/bin/xkbbell
/bin/xkbcomp
/bin/xkbevd
/bin/xkbprint
/bin/xkbvleds
/bin/xkbwatch
/bin/xkill
/bin/xload
/bin/xlogo
/bin/xlsatoms
/bin/xlsclients
/bin/xlsfonts
/bin/xmag
/bin/xman
/bin/xmessage
/bin/xml2ag
/bin/xmlcatalog
/bin/xmllint
/bin/xmodmap
/bin/xmore
/bin/xorriso
/bin/xprintidle
/bin/xprop
/bin/xrandr
/bin/xrdb
/bin/xrefresh
/bin/xsel
/bin/xset
/bin/xsetmode
/bin/xsetpointer
/bin/xsetroot
/bin/xsetwacom
/bin/xsm
/bin/xstdcmap
/bin/xterm
/bin/xvidtune
/bin/xvinfo
/bin/Xwayland
/bin/xwd
/bin/xwininfo
/bin/xwud
/bin/xxd
/bin/xz
/bin/yelp
/bin/yes
/bin/zdump
/bin/zenity
/bin/zip
/bin/zipcloak
/bin/zipinfo
/bin/zipnote
/bin/zipsplit
/bin/zsh
/bin/zstd
/usr/bin/[
/usr/bin/aa-enabled
/usr/bin/aa-exec
/usr/bin/aa-features-abi
/usr/bin/aconnect
/usr/bin/acyclic
/usr/bin/addpart
/usr/bin/airscan-discover
/usr/bin/alsabat
/usr/bin/alsaloop
/usr/bin/alsamixer
/usr/bin/alsatplg
/usr/bin/alsaucm
/usr/bin/amidi
/usr/bin/amixer
/usr/bin/apgbfm
/usr/bin/aplay
/usr/bin/aplaymidi
/usr/bin/appres
/usr/bin/appstreamcli
/usr/bin/apt
/usr/bin/apt-cache
/usr/bin/apt-cdrom
/usr/bin/apt-config
/usr/bin/apt-extracttemplates
/usr/bin/apt-ftparchive
/usr/bin/apt-get
/usr/bin/apt-mark
/usr/bin/apt-sortpkgs
/usr/bin/arch
/usr/bin/arecordmidi
/usr/bin/aria_chk
/usr/bin/aria_dump_log
/usr/bin/aria_ftdump
/usr/bin/aria_pack
/usr/bin/aria_read_log
/usr/bin/as31
/usr/bin/aseqdump
/usr/bin/aseqnet
/usr/bin/aspell
/usr/bin/at
/usr/bin/atobm
/usr/bin/autogen
/usr/bin/avahi-browse
/usr/bin/avahi-publish
/usr/bin/avahi-resolve
/usr/bin/avahi-set-host-name
/usr/bin/avinfo
/usr/bin/axfer
/usr/bin/b2sum
/usr/bin/baobab
/usr/bin/base32
/usr/bin/base64
/usr/bin/basename
/usr/bin/basenc
/usr/bin/bash
/usr/bin/bc
/usr/bin/bcomps
/usr/bin/bdftopcf
/usr/bin/bdftruncate
/usr/bin/bison
/usr/bin/bitmap
/usr/bin/blender
/usr/bin/blender-thumbnailer
/usr/bin/bluemoon
/usr/bin/bluetoothctl
/usr/bin/bluetooth-sendto
/usr/bin/bmtoa
/usr/bin/boltctl
/usr/bin/bootctl
/usr/bin/broadwayd
/usr/bin/btattach
/usr/bin/btmgmt
/usr/bin/btmon
/usr/bin/btrfs
/usr/bin/btrfs-convert
/usr/bin/btrfs-find-root
/usr/bin/btrfs-image
/usr/bin/btrfs-map-logical
/usr/bin/btrfs-select-super
/usr/bin/btrfstune
/usr/bin/bunzip2
/usr/bin/busctl
/usr/bin/busybox
/usr/bin/bwrap
/usr/bin/bzcat
/usr/bin/bzip2
/usr/bin/bzip2recover
/usr/bin/cabal
/usr/bin/canberra-gtk-play
/usr/bin/cancel
/usr/bin/capinfos
/usr/bin/captype
/usr/bin/cargo
/usr/bin/cat
/usr/bin/catman
/usr/bin/ccomps
/usr/bin/cct
/usr/bin/cd-create-profile
/usr/bin/cd-fix-profile
/usr/bin/cd-iccdump
/usr/bin/cd-it8
/usr/bin/cgi-fcgi
/usr/bin/cg_merge
/usr/bin/chacl
/usr/bin/chage
/usr/bin/chattr
/usr/bin/chcon
/usr/bin/cheese
/usr/bin/chfn
/usr/bin/chg
/usr/bin/chgrp
/usr/bin/chmod
/usr/bin/choom
/usr/bin/chown
/usr/bin/chronyc
/usr/bin/chrt
/usr/bin/chsh
/usr/bin/chvt
/usr/bin/ciptool
/usr/bin/cksum
/usr/bin/clear
/usr/bin/clear_console
/usr/bin/cluster
/usr/bin/cmake
/usr/bin/cmp
/usr/bin/codepage
/usr/bin/col
/usr/bin/colcrt
/usr/bin/colormgr
/usr/bin/colrm
/usr/bin/column
/usr/bin/columns
/usr/bin/comm
/usr/bin/containerd
/usr/bin/containerd-shim-runc-v2
/usr/bin/cp
/usr/bin/cpack
/usr/bin/cpio
/usr/bin/cppcheck
/usr/bin/crontab
/usr/bin/cs2cs
/usr/bin/csplit
/usr/bin/ctags.emacs
/usr/bin/ctest
/usr/bin/ctr
/usr/bin/cupstestppd
/usr/bin/curl
/usr/bin/cut
/usr/bin/cvt
/usr/bin/cvtsudoers
/usr/bin/darcs
/usr/bin/dash
/usr/bin/date
/usr/bin/dbus-cleanup-sockets
/usr/bin/dbus-daemon
/usr/bin/dbus-monitor
/usr/bin/dbus-run-session
/usr/bin/dbus-send
/usr/bin/dbus-update-activation-environment
/usr/bin/dbus-uuidgen
/usr/bin/dbxtool
/usr/bin/dconf
/usr/bin/dd
/usr/bin/deallocvt
/usr/bin/debian-distro-info
/usr/bin/delaunay
/usr/bin/delpart
/usr/bin/delv
/usr/bin/derb
/usr/bin/desktop-file-install
/usr/bin/desktop-file-validate
/usr/bin/df
/usr/bin/dfu-tool
/usr/bin/diff
/usr/bin/diff3
/usr/bin/diffimg
/usr/bin/dig
/usr/bin/dijkstra
/usr/bin/dir
/usr/bin/dircolors
/usr/bin/dirmngr
/usr/bin/dirmngr-client
/usr/bin/dirname
/usr/bin/dmesg
/usr/bin/dm-tool
/usr/bin/docker
/usr/bin/dockerd
/usr/bin/docker-proxy
/usr/bin/dot_builtins
/usr/bin/dpkg
/usr/bin/dpkg-deb
/usr/bin/dpkg-divert
/usr/bin/dpkg-query
/usr/bin/dpkg-split
/usr/bin/dpkg-statoverride
/usr/bin/dpkg-trigger
/usr/bin/du
/usr/bin/dumpcap
/usr/bin/dumpkeys
/usr/bin/dumpsexp
/usr/bin/ebrowse.emacs
/usr/bin/echo
/usr/bin/ed
/usr/bin/edgepaint
/usr/bin/editcap
/usr/bin/editres
/usr/bin/efibootdump
/usr/bin/efibootmgr
/usr/bin/eject
/usr/bin/emacsclient.emacs
/usr/bin/emacs-gtk
/usr/bin/enchant-2
/usr/bin/enchant-lsmod-2
/usr/bin/env
/usr/bin/envsubst
/usr/bin/eog
/usr/bin/eqn
/usr/bin/errno
/usr/bin/etags.emacs
/usr/bin/evince
/usr/bin/evince-previewer
/usr/bin/evince-thumbnailer
/usr/bin/expand
/usr/bin/expiry
/usr/bin/expr
/usr/bin/factor
/usr/bin/faillog
/usr/bin/faked-sysv
/usr/bin/faked-tcp
/usr/bin/fallocate
/usr/bin/false
/usr/bin/fbstat
/usr/bin/fbsvcmgr
/usr/bin/fc-cache
/usr/bin/fc-cat
/usr/bin/fc-conflist
/usr/bin/fc-list
/usr/bin/fc-match
/usr/bin/fc-pattern
/usr/bin/fc-query
/usr/bin/fc-scan
/usr/bin/fc-validate
/usr/bin/fgconsole
/usr/bin/filan
/usr/bin/file
/usr/bin/file2brl
/usr/bin/file-roller
/usr/bin/fincore
/usr/bin/find
/usr/bin/findmnt
/usr/bin/fish
/usr/bin/fish_indent
/usr/bin/fish_key_reader
/usr/bin/flex
/usr/bin/flock
/usr/bin/fmt
/usr/bin/fold
/usr/bin/fonttosfnt
/usr/bin/free
/usr/bin/funzip
/usr/bin/fuser
/usr/bin/fusermount3
/usr/bin/fwupdate
/usr/bin/fwupdmgr
/usr/bin/fwupdtool
/usr/bin/gamma4scanimage
/usr/bin/gapplication
/usr/bin/gatttool
/usr/bin/gawk
/usr/bin/gbak
/usr/bin/gc
/usr/bin/gcalccmd
/usr/bin/gcr-viewer
/usr/bin/gdb
/usr/bin/gdbus
/usr/bin/gdk-pixbuf-csource
/usr/bin/gdk-pixbuf-pixdata
/usr/bin/gdk-pixbuf-thumbnailer
/usr/bin/gdmflexiserver
/usr/bin/gedit
/usr/bin/genbrk
/usr/bin/gencat
/usr/bin/gencfu
/usr/bin/gencnval
/usr/bin/gendict
/usr/bin/genrb
/usr/bin/geod
/usr/bin/getconf
/usr/bin/getdefs
/usr/bin/getent
/usr/bin/getfacl
/usr/bin/getkeycodes
/usr/bin/getopt
/usr/bin/gettext
/usr/bin/gfix
/usr/bin/gie
/usr/bin/gimp-2.10
/usr/bin/gimp-console-2.10
/usr/bin/gimp-test-clipboard-2.0
/usr/bin/gio
/usr/bin/g-ir-compiler
/usr/bin/g-ir-generate
/usr/bin/g-ir-inspect
/usr/bin/git
/usr/bin/git-lfs
/usr/bin/git-shell
/usr/bin/gjs-console
/usr/bin/gkbd-keyboard-display
/usr/bin/glewinfo
/usr/bin/glib-compile-resources
/usr/bin/glmark2
/usr/bin/gml2gv
/usr/bin/gnome-calculator
/usr/bin/gnome-calendar
/usr/bin/gnome-contacts
/usr/bin/gnome-control-center
/usr/bin/gnome-disk-image-mounter
/usr/bin/gnome-disks
/usr/bin/gnome-extensions
/usr/bin/gnome-font-viewer
/usr/bin/gnome-keyring-3
/usr/bin/gnome-keyring-daemon
/usr/bin/gnome-logs
/usr/bin/gnome-power-statistics
/usr/bin/gnome-screensaver
/usr/bin/gnome-screensaver-command
/usr/bin/gnome-session-inhibit
/usr/bin/gnome-session-properties
/usr/bin/gnome-session-quit
/usr/bin/gnome-shell
/usr/bin/gnome-system-monitor
/usr/bin/gnome-terminal.real
/usr/bin/gnome-thumbnail-font
/usr/bin/gnome-todo
/usr/bin/gobject-query
/usr/bin/gpasswd
/usr/bin/gpg
/usr/bin/gpg-agent
/usr/bin/gpgcompose
/usr/bin/gpgconf
/usr/bin/gpg-connect-agent
/usr/bin/gpgparsemail
/usr/bin/gpgsm
/usr/bin/gpgsplit
/usr/bin/gpgtar
/usr/bin/gpgv
/usr/bin/gpg-wks-server
/usr/bin/gpre
/usr/bin/gpu-manager
/usr/bin/graphml2gv
/usr/bin/grdctl
/usr/bin/grep
/usr/bin/gresource
/usr/bin/groff
/usr/bin/grops
/usr/bin/grotty
/usr/bin/groups
/usr/bin/grub-editenv
/usr/bin/grub-file
/usr/bin/grub-fstest
/usr/bin/grub-glue-efi
/usr/bin/grub-menulst2cfg
/usr/bin/grub-mkfont
/usr/bin/grub-mkimage
/usr/bin/grub-mklayout
/usr/bin/grub-mknetdir
/usr/bin/grub-mkpasswd-pbkdf2
/usr/bin/grub-mkrelpath
/usr/bin/grub-mkrescue
/usr/bin/grub-mkstandalone
/usr/bin/grub-mount
/usr/bin/grub-render-label
/usr/bin/grub-script-check
/usr/bin/grub-syslinux2cfg
/usr/bin/gs
/usr/bin/gsec
/usr/bin/gsettings
/usr/bin/gst-device-monitor-1.0
/usr/bin/gst-discoverer-1.0
/usr/bin/gst-inspect-1.0
/usr/bin/gst-launch-1.0
/usr/bin/gst-play-1.0
/usr/bin/gst-stats-1.0
/usr/bin/gst-tester-1.0
/usr/bin/gst-typefind-1.0
/usr/bin/gtester
/usr/bin/gtf
/usr/bin/gtk4-builder-tool
/usr/bin/gtk4-encode-symbolic-svg
/usr/bin/gtk4-launch
/usr/bin/gtk4-query-settings
/usr/bin/gtk4-update-icon-cache
/usr/bin/gtk-builder-tool
/usr/bin/gtk-encode-symbolic-svg
/usr/bin/gtk-launch
/usr/bin/gtk-query-settings
/usr/bin/gtk-update-icon-cache
/usr/bin/gts2dxf
/usr/bin/gts2oogl
/usr/bin/gts2stl
/usr/bin/gts2xyz
/usr/bin/gtscheck
/usr/bin/gtscompare
/usr/bin/gv2gml
/usr/bin/gvcolor
/usr/bin/gvgen
/usr/bin/gvmap
/usr/bin/gvpack
/usr/bin/gvpr
/usr/bin/gxl2gv
/usr/bin/gzip
/usr/bin/hardlink
/usr/bin/hciattach
/usr/bin/hciconfig
/usr/bin/hcitool
/usr/bin/head
/usr/bin/hex2hcd
/usr/bin/hexchat
/usr/bin/hexdump
/usr/bin/hmac256
/usr/bin/host
/usr/bin/hostid
/usr/bin/hostname
/usr/bin/hostnamectl
/usr/bin/htop
/usr/bin/ibus
/usr/bin/ibus-daemon
/usr/bin/iceauth
/usr/bin/ico
/usr/bin/iconv
/usr/bin/icuexportdata
/usr/bin/icuinfo
/usr/bin/id
/usr/bin/iecset
/usr/bin/ifdata
/usr/bin/ifne
/usr/bin/info
/usr/bin/infocmp
/usr/bin/innochecksum
/usr/bin/inputattach
/usr/bin/install
/usr/bin/install-info
/usr/bin/intel-virtual-output
/usr/bin/ionice
/usr/bin/ip
/usr/bin/ipcmk
/usr/bin/ipcrm
/usr/bin/ipcs
/usr/bin/ippfind
/usr/bin/ipptool
/usr/bin/ischroot
/usr/bin/isdv4-serial-debugger
/usr/bin/isdv4-serial-inputattach
/usr/bin/isql-fb
/usr/bin/isutf8
/usr/bin/join
/usr/bin/journalctl
/usr/bin/jq
/usr/bin/k5start
/usr/bin/kadmin
/usr/bin/kbdinfo
/usr/bin/kbd_mode
/usr/bin/kbuildsycoca5
/usr/bin/kbxutil
/usr/bin/kcachegrind
/usr/bin/kcookiejar5
/usr/bin/kded5
/usr/bin/kde-geo-uri-handler
/usr/bin/kdestroy
/usr/bin/keyctl
/usr/bin/kglobalaccel5
/usr/bin/kiconfinder5
/usr/bin/kill
/usr/bin/killall
/usr/bin/kinit
/usr/bin/klist
/usr/bin/kmod
/usr/bin/kmodsign
/usr/bin/kpasswd
/usr/bin/kquitapp5
/usr/bin/kreadconfig5
/usr/bin/krenew
/usr/bin/ksu
/usr/bin/kswitch
/usr/bin/ktelnetservice5
/usr/bin/ktrash5
/usr/bin/ktutil
/usr/bin/kvno
/usr/bin/kwalletd5
/usr/bin/kwallet-query
/usr/bin/kwriteconfig5
/usr/bin/l2ping
/usr/bin/l2test
/usr/bin/last
/usr/bin/lastlog
/usr/bin/lckdo
/usr/bin/ldapcompare
/usr/bin/ldapdelete
/usr/bin/ldapexop
/usr/bin/ldapmodify
/usr/bin/ldapmodrdn
/usr/bin/ldappasswd
/usr/bin/ldapsearch
/usr/bin/ldapurl
/usr/bin/ldapwhoami
/usr/bin/ldrdf
/usr/bin/lefty
/usr/bin/less
/usr/bin/lessecho
/usr/bin/lesskey
/usr/bin/lexgrog
/usr/bin/libwacom-list-devices
/usr/bin/libwacom-list-local-devices
/usr/bin/link
/usr/bin/listres
/usr/bin/ln
/usr/bin/lnstat
/usr/bin/loadkeys
/usr/bin/loadunimap
/usr/bin/locale
/usr/bin/locale-check
/usr/bin/localectl
/usr/bin/localedef
/usr/bin/logger
/usr/bin/login
/usr/bin/loginctl
/usr/bin/logname
/usr/bin/look
/usr/bin/lowntfs-3g
/usr/bin/lp
/usr/bin/lpoptions
/usr/bin/lp_solve
/usr/bin/lpstat
/usr/bin/ls
/usr/bin/lsattr
/usr/bin/lsblk
/usr/bin/lscpu
/usr/bin/lshw
/usr/bin/lsipc
/usr/bin/lslocks
/usr/bin/lslogins
/usr/bin/lsmem
/usr/bin/lsns
/usr/bin/lsof
/usr/bin/lspci
/usr/bin/lsusb
/usr/bin/lua5.4
/usr/bin/luac5.4
/usr/bin/luit
/usr/bin/lzmainfo
/usr/bin/m4
/usr/bin/machinectl
/usr/bin/make
/usr/bin/makeconv
/usr/bin/man
/usr/bin/mandb
/usr/bin/manpath
/usr/bin/man-recode
/usr/bin/mapscrn
/usr/bin/mariadb
/usr/bin/mariadb-admin
/usr/bin/mariadb-binlog
/usr/bin/mariadb-check
/usr/bin/mariadb-conv
/usr/bin/mariadbd-safe-helper
/usr/bin/mariadb-dump
/usr/bin/mariadb-import
/usr/bin/mariadb-plugin
/usr/bin/mariadb-show
/usr/bin/mariadb-slap
/usr/bin/mariadb-tzinfo-to-sql
/usr/bin/mariadb-upgrade
/usr/bin/mariadb-waitpid
/usr/bin/mawk
/usr/bin/mcookie
/usr/bin/md5sum
/usr/bin/mdig
/usr/bin/memusagestat
/usr/bin/mergecap
/usr/bin/mesg
/usr/bin/mingle
/usr/bin/mispipe
/usr/bin/mkdir
/usr/bin/mkfifo
/usr/bin/mkfontscale
/usr/bin/mknod
/usr/bin/mksquashfs
/usr/bin/mktemp
/usr/bin/mm2gv
/usr/bin/mmcli
/usr/bin/mmdbresolve
/usr/bin/mokutil
/usr/bin/monitor-sensor
/usr/bin/more
/usr/bin/mount
/usr/bin/mountpoint
/usr/bin/mpicalc
/usr/bin/mt-gnu
/usr/bin/mtr
/usr/bin/mtr-packet
/usr/bin/mv
/usr/bin/myisamchk
/usr/bin/myisam_ftdump
/usr/bin/myisamlog
/usr/bin/myisampack
/usr/bin/my_print_defaults
/usr/bin/namei
/usr/bin/nano
/usr/bin/nasm
/usr/bin/nautilus
/usr/bin/nautilus-autorun-software
/usr/bin/nautilus-sendto
/usr/bin/nbackup
/usr/bin/ncdu
/usr/bin/nc.openbsd
/usr/bin/ndisasm
/usr/bin/netstat
/usr/bin/networkctl
/usr/bin/newgidmap
/usr/bin/newgrp
/usr/bin/newuidmap
/usr/bin/ngettext
/usr/bin/nice
/usr/bin/nl
/usr/bin/nm-applet
/usr/bin/nmcli
/usr/bin/nm-connection-editor
/usr/bin/nm-online
/usr/bin/nmtui
/usr/bin/node
/usr/bin/nohup
/usr/bin/nop
/usr/bin/notify-send
/usr/bin/nproc
/usr/bin/nsenter
/usr/bin/nslookup
/usr/bin/nstat
/usr/bin/nsupdate
/usr/bin/ntfs-3g
/usr/bin/ntfs-3g.probe
/usr/bin/ntfscat
/usr/bin/ntfscluster
/usr/bin/ntfscmp
/usr/bin/ntfsdecrypt
/usr/bin/ntfsfallocate
/usr/bin/ntfsfix
/usr/bin/ntfsinfo
/usr/bin/ntfsls
/usr/bin/ntfsmove
/usr/bin/ntfsrecover
/usr/bin/ntfssecaudit
/usr/bin/ntfstruncate
/usr/bin/ntfsusermap
/usr/bin/ntfswipe
/usr/bin/numfmt
/usr/bin/numlockx
/usr/bin/nvim
/usr/bin/obexctl
/usr/bin/ocamlcmt
/usr/bin/ocamlc.opt
/usr/bin/ocamlcp.opt
/usr/bin/ocamldep.opt
/usr/bin/ocamldoc.opt
/usr/bin/ocamllex.opt
/usr/bin/ocamlmklib.opt
/usr/bin/ocamlmktop.opt
/usr/bin/ocamlobjinfo.opt
/usr/bin/ocamlopt.opt
/usr/bin/ocamloptp.opt
/usr/bin/ocamlprof.opt
/usr/bin/ocamlrun
/usr/bin/ocamlrund
/usr/bin/ocamlruni
/usr/bin/ocamlyacc
/usr/bin/oclock
/usr/bin/od
/usr/bin/ollama
/usr/bin/opam
/usr/bin/opam-installer
/usr/bin/openssl
/usr/bin/openvt
/usr/bin/p11-kit
/usr/bin/pacat
/usr/bin/pacmd
/usr/bin/pactl
/usr/bin/pango-list
/usr/bin/pango-segmentation
/usr/bin/pango-view
/usr/bin/paperconf
/usr/bin/parallel
/usr/bin/partx
/usr/bin/passwd
/usr/bin/paste
/usr/bin/pasuspender
/usr/bin/patch
/usr/bin/pathchk
/usr/bin/pax11publish
/usr/bin/pdfattach
/usr/bin/pdfdetach
/usr/bin/pdffonts
/usr/bin/pdfimages
/usr/bin/pdfinfo
/usr/bin/pdfseparate
/usr/bin/pdfsig
/usr/bin/pdftocairo
/usr/bin/pdftohtml
/usr/bin/pdftoppm
/usr/bin/pdftops
/usr/bin/pdftotext
/usr/bin/pdfunite
/usr/bin/pee
/usr/bin/peekfd
/usr/bin/perl
/usr/bin/perl5.34.0
/usr/bin/perl5.34-x86_64-linux-gnu
/usr/bin/perror
/usr/bin/pgrep
/usr/bin/php8.1
/usr/bin/pic
/usr/bin/pidwait
/usr/bin/pigz
/usr/bin/pinentry-curses
/usr/bin/pinentry-gnome3
/usr/bin/ping
/usr/bin/pinky
/usr/bin/pipewire
/usr/bin/pipewire-media-session
/usr/bin/pkaction
/usr/bin/pkcheck
/usr/bin/pkexec
/usr/bin/pkg-config
/usr/bin/pkgdata
/usr/bin/pkttyagent
/usr/bin/pldd
/usr/bin/plymouth
/usr/bin/pmap
/usr/bin/pngfix
/usr/bin/png-fix-itxt
/usr/bin/portablectl
/usr/bin/ppdc
/usr/bin/ppdhtml
/usr/bin/ppdi
/usr/bin/ppdmerge
/usr/bin/ppdpo
/usr/bin/pr
/usr/bin/preconv
/usr/bin/prezip-bin
/usr/bin/printenv
/usr/bin/printf
/usr/bin/prlimit
/usr/bin/procan
/usr/bin/proj
/usr/bin/projinfo
/usr/bin/projsync
/usr/bin/prometheus-node-exporter
/usr/bin/protocoltojson
/usr/bin/proxy
/usr/bin/prtstat
/usr/bin/prune
/usr/bin/ps
/usr/bin/psfxtable
/usr/bin/pslog
/usr/bin/pstree
/usr/bin/ptx
/usr/bin/pulseaudio
/usr/bin/pw-cat
/usr/bin/pw-cli
/usr/bin/pwd
/usr/bin/pw-dot
/usr/bin/pw-dump
/usr/bin/pwdx
/usr/bin/pw-link
/usr/bin/pw-loopback
/usr/bin/pw-metadata
/usr/bin/pw-mididump
/usr/bin/pw-mon
/usr/bin/pw-profiler
/usr/bin/pw-reserve
/usr/bin/pw-top
/usr/bin/python3.10
/usr/bin/python3.7
/usr/bin/python3.7m
/usr/bin/pzstd
/usr/bin/qemu-img
/usr/bin/qemu-io
/usr/bin/qemu-nbd
/usr/bin/qemu-pr-helper
/usr/bin/qemu-storage-daemon
/usr/bin/qemu-system-aarch64
/usr/bin/qemu-system-alpha
/usr/bin/qemu-system-arm
/usr/bin/qemu-system-avr
/usr/bin/qemu-system-cris
/usr/bin/qemu-system-hppa
/usr/bin/qemu-system-i386
/usr/bin/qemu-system-m68k
/usr/bin/qemu-system-microblaze
/usr/bin/qemu-system-microblazeel
/usr/bin/qemu-system-mips
/usr/bin/qemu-system-mips64
/usr/bin/qemu-system-mips64el
/usr/bin/qemu-system-mipsel
/usr/bin/qemu-system-nios2
/usr/bin/qemu-system-or1k
/usr/bin/qemu-system-ppc
/usr/bin/qemu-system-ppc64
/usr/bin/qemu-system-riscv32
/usr/bin/qemu-system-riscv64
/usr/bin/qemu-system-rx
/usr/bin/qemu-system-s390x
/usr/bin/qemu-system-sh4
/usr/bin/qemu-system-sh4eb
/usr/bin/qemu-system-sparc
/usr/bin/qemu-system-sparc64
/usr/bin/qemu-system-tricore
/usr/bin/qemu-system-x86_64
/usr/bin/qemu-system-x86_64-microvm
/usr/bin/qemu-system-xtensa
/usr/bin/qemu-system-xtensaeb
/usr/bin/qtchooser
/usr/bin/qtcreator
/usr/bin/quota
/usr/bin/quotasync
/usr/bin/randpkt
/usr/bin/rawshark
/usr/bin/rctest
/usr/bin/rdf2bin
/usr/bin/rdfdump
/usr/bin/rdflib
/usr/bin/rdma
/usr/bin/rdx
/usr/bin/readlink
/usr/bin/realpath
/usr/bin/redis-benchmark
/usr/bin/redis-check-aof
/usr/bin/redis-check-rdb
/usr/bin/redis-cli
/usr/bin/remmina
/usr/bin/remote-viewer
/usr/bin/rendercheck
/usr/bin/renice
/usr/bin/reordercap
/usr/bin/replace
/usr/bin/resize
/usr/bin/resizecons
/usr/bin/resizepart
/usr/bin/resolvectl
/usr/bin/resolveip
/usr/bin/resolve_stack_dump
/usr/bin/rev
/usr/bin/rfcomm
/usr/bin/rg
/usr/bin/rm
/usr/bin/rmdir
/usr/bin/rootlesskit
/usr/bin/rpcgen
/usr/bin/rpcinfo
/usr/bin/rsync
/usr/bin/ruby3.0
/usr/bin/runc
/usr/bin/runcon
/usr/bin/run-parts
/usr/bin/rustc
/usr/bin/rustdoc
/usr/bin/rygel
/usr/bin/sane-find-scanner
/usr/bin/sbattach
/usr/bin/sbkeysync
/usr/bin/sbsiglist
/usr/bin/sbsign
/usr/bin/sbvarsign
/usr/bin/sbverify
/usr/bin/scanimage
/usr/bin/sccmap
/usr/bin/scp
/usr/bin/screen
/usr/bin/screendump
/usr/bin/script
/usr/bin/scriptlive
/usr/bin/scriptreplay
/usr/bin/sdiff
/usr/bin/sdptool
/usr/bin/sed
/usr/bin/seq
/usr/bin/session-migration
/usr/bin/sessreg
/usr/bin/setarch
/usr/bin/setfacl
/usr/bin/setfont
/usr/bin/setkeycodes
/usr/bin/setleds
/usr/bin/setlogcons
/usr/bin/setmetamode
/usr/bin/setpci
/usr/bin/setpriv
/usr/bin/setsid
/usr/bin/setterm
/usr/bin/setxkbmap
/usr/bin/sftp
/usr/bin/sg_bg_ctl
/usr/bin/sg_compare_and_write
/usr/bin/sg_copy_results
/usr/bin/sg_dd
/usr/bin/sg_decode_sense
/usr/bin/sg_emc_trespass
/usr/bin/sg_format
/usr/bin/sg_get_config
/usr/bin/sg_get_elem_status
/usr/bin/sg_get_lba_status
/usr/bin/sg_ident
/usr/bin/sginfo
/usr/bin/sg_inq
/usr/bin/sg_logs
/usr/bin/sg_luns
/usr/bin/sg_map
/usr/bin/sg_map26
/usr/bin/sgm_dd
/usr/bin/sg_modes
/usr/bin/sg_opcodes
/usr/bin/sgp_dd
/usr/bin/sg_persist
/usr/bin/sg_prevent
/usr/bin/sg_raw
/usr/bin/sg_rbuf
/usr/bin/sg_rdac
/usr/bin/sg_read
/usr/bin/sg_read_attr
/usr/bin/sg_read_block_limits
/usr/bin/sg_read_buffer
/usr/bin/sg_readcap
/usr/bin/sg_read_long
/usr/bin/sg_reassign
/usr/bin/sg_referrals
/usr/bin/sg_rep_pip
/usr/bin/sg_rep_zones
/usr/bin/sg_requests
/usr/bin/sg_reset
/usr/bin/sg_reset_wp
/usr/bin/sg_rmsn
/usr/bin/sg_rtpg
/usr/bin/sg_safte
/usr/bin/sg_sanitize
/usr/bin/sg_sat_identify
/usr/bin/sg_sat_phy_event
/usr/bin/sg_sat_read_gplog
/usr/bin/sg_sat_set_features
/usr/bin/sg_scan
/usr/bin/sg_seek
/usr/bin/sg_senddiag
/usr/bin/sg_ses
/usr/bin/sg_ses_microcode
/usr/bin/sg_start
/usr/bin/sg_stpg
/usr/bin/sg_stream_ctl
/usr/bin/sg_sync
/usr/bin/sg_test_rwbuf
/usr/bin/sg_timestamp
/usr/bin/sg_turs
/usr/bin/sg_unmap
/usr/bin/sg_verify
/usr/bin/sg_vpd
/usr/bin/sg_write_buffer
/usr/bin/sg_write_long
/usr/bin/sg_write_same
/usr/bin/sg_write_verify
/usr/bin/sg_write_x
/usr/bin/sg_wr_mode
/usr/bin/sg_xcopy
/usr/bin/sg_zone
/usr/bin/sha1sum
/usr/bin/sha224sum
/usr/bin/sha256sum
/usr/bin/sha384sum
/usr/bin/sha512sum
/usr/bin/sharkd
/usr/bin/showconsolefont
/usr/bin/showkey
/usr/bin/showrgb
/usr/bin/shred
/usr/bin/shuf
/usr/bin/siege
/usr/bin/simplescreenrecorder
/usr/bin/skill
/usr/bin/slabtop
/usr/bin/sleep
/usr/bin/slirp4netns
/usr/bin/smproxy
/usr/bin/snap
/usr/bin/snapfuse
/usr/bin/socat
/usr/bin/soelim
/usr/bin/sort
/usr/bin/spa-acp-tool
/usr/bin/spa-inspect
/usr/bin/spa-json-dump
/usr/bin/spa-monitor
/usr/bin/spa-resample
/usr/bin/spd-say
/usr/bin/spdsend
/usr/bin/speaker-test
/usr/bin/speech-dispatcher
/usr/bin/spice-vdagent
/usr/bin/split
/usr/bin/splitfont
/usr/bin/sponge
/usr/bin/sprof
/usr/bin/sqlite3
/usr/bin/ss
/usr/bin/ssh
/usr/bin/ssh-add
/usr/bin/ssh-agent
/usr/bin/ssh-keygen
/usr/bin/ssh-keyscan
/usr/bin/sss_ssh_authorizedkeys
/usr/bin/sss_ssh_knownhostsproxy
/usr/bin/stat
/usr/bin/stdbuf
/usr/bin/stl2gts
/usr/bin/strace
/usr/bin/stty
/usr/bin/su
/usr/bin/sudoreplay
/usr/bin/sum
/usr/bin/swtpm
/usr/bin/swtpm_bios
/usr/bin/swtpm_cert
/usr/bin/swtpm_ioctl
/usr/bin/swtpm_setup
/usr/bin/sync
/usr/bin/systemctl
/usr/bin/systemd-analyze
/usr/bin/systemd-ask-password
/usr/bin/systemd-cat
/usr/bin/systemd-cgls
/usr/bin/systemd-cgtop
/usr/bin/systemd-cryptenroll
/usr/bin/systemd-delta
/usr/bin/systemd-detect-virt
/usr/bin/systemd-dissect
/usr/bin/systemd-escape
/usr/bin/systemd-hwdb
/usr/bin/systemd-id128
/usr/bin/systemd-inhibit
/usr/bin/systemd-machine-id-setup
/usr/bin/systemd-mount
/usr/bin/systemd-notify
/usr/bin/systemd-nspawn
/usr/bin/systemd-path
/usr/bin/systemd-run
/usr/bin/systemd-socket-activate
/usr/bin/systemd-stdio-bridge
/usr/bin/systemd-sysext
/usr/bin/systemd-sysusers
/usr/bin/systemd-tmpfiles
/usr/bin/systemd-tty-ask-password-agent
/usr/bin/tabs
/usr/bin/tac
/usr/bin/tail
/usr/bin/tar
/usr/bin/taskset
/usr/bin/tbl
/usr/bin/tclsh8.6
/usr/bin/tcpdump
/usr/bin/tee
/usr/bin/telnet.netkit
/usr/bin/tempfile
/usr/bin/test
/usr/bin/text2pcap
/usr/bin/tic
/usr/bin/time
/usr/bin/timedatectl
/usr/bin/timeout
/usr/bin/tload
/usr/bin/tmux
/usr/bin/tnftp
/usr/bin/toe
/usr/bin/top
/usr/bin/totem
/usr/bin/totem-video-thumbnailer
/usr/bin/touch
/usr/bin/tput
/usr/bin/tr
/usr/bin/tracepath
/usr/bin/tracker3
/usr/bin/transform
/usr/bin/transset
/usr/bin/tred
/usr/bin/tree
/usr/bin/troff
/usr/bin/true
/usr/bin/truncate
/usr/bin/trust
/usr/bin/tset
/usr/bin/tsort
/usr/bin/tty
/usr/bin/ubuntu-distro-info
/usr/bin/ubuntu-report
/usr/bin/uclampset
/usr/bin/uconv
/usr/bin/ucs2any
/usr/bin/udevadm
/usr/bin/udisksctl
/usr/bin/ul
/usr/bin/umax_pp
/usr/bin/umount
/usr/bin/uname
/usr/bin/unexpand
/usr/bin/unflatten
/usr/bin/uniq
/usr/bin/unity-scope-loader
/usr/bin/unlink
/usr/bin/unpigz
/usr/bin/unshare
/usr/bin/unsquashfs
/usr/bin/unzip
/usr/bin/unzipsfx
/usr/bin/update-alternatives
/usr/bin/update-desktop-database
/usr/bin/update-mime-database
/usr/bin/upower
/usr/bin/uptime
/usr/bin/usbhid-dump
/usr/bin/usbreset
/usr/bin/users
/usr/bin/utmpdump
/usr/bin/uuidgen
/usr/bin/uuidparse
/usr/bin/valgrind.bin
/usr/bin/valgrind-di-server
/usr/bin/valgrind-listener
/usr/bin/VBoxDTrace
/usr/bin/vdir
/usr/bin/VGAuthService
/usr/bin/vgdb
/usr/bin/viewres
/usr/bin/vim.basic
/usr/bin/vim.tiny
/usr/bin/virsh
/usr/bin/virt-admin
/usr/bin/virt-host-validate
/usr/bin/virt-pki-query-dn
/usr/bin/virt-qemu-run
/usr/bin/virt-ssh-helper
/usr/bin/virt-viewer
/usr/bin/visualinfo
/usr/bin/vkcube
/usr/bin/vkcubepp
/usr/bin/vlc
/usr/bin/vlc-wrapper
/usr/bin/vmhgfs-fuse
/usr/bin/vmstat
/usr/bin/vmtoolsd
/usr/bin/vmware-alias-import
/usr/bin/vmware-checkvm
/usr/bin/vmwarectrl
/usr/bin/vmware-hgfsclient
/usr/bin/vmware-namespace-cmd
/usr/bin/vmware-rpctool
/usr/bin/vmware-toolbox-cmd
/usr/bin/vmware-vgauth-cmd
/usr/bin/vmware-vmblock-fuse
/usr/bin/vmware-xferlogs
/usr/bin/vulkaninfo
/usr/bin/w
/usr/bin/wall
/usr/bin/watch
/usr/bin/watchgnupg
/usr/bin/wayland-scanner
/usr/bin/wc
/usr/bin/wdctl
/usr/bin/weechat
/usr/bin/wget
/usr/bin/whatis
/usr/bin/whereis
/usr/bin/whiptail
/usr/bin/who
/usr/bin/whoami
/usr/bin/whoopsie
/usr/bin/whoopsie-preferences
/usr/bin/wireshark
/usr/bin/wish8.6
/usr/bin/word-list-compress
/usr/bin/wpa_passphrase
/usr/bin/write.ul
/usr/bin/x11perf
/usr/bin/x11vnc
/usr/bin/x86_64-linux-gnu-addr2line
/usr/bin/x86_64-linux-gnu-ar
/usr/bin/x86_64-linux-gnu-as
/usr/bin/x86_64-linux-gnu-c++filt
/usr/bin/x86_64-linux-gnu-cpp-11
/usr/bin/x86_64-linux-gnu-cpp-12
/usr/bin/x86_64-linux-gnu-dwp
/usr/bin/x86_64-linux-gnu-elfedit
/usr/bin/x86_64-linux-gnu-g++-11
/usr/bin/x86_64-linux-gnu-g++-12
/usr/bin/x86_64-linux-gnu-gcc-11
/usr/bin/x86_64-linux-gnu-gcc-12
/usr/bin/x86_64-linux-gnu-gcc-ar-11
/usr/bin/x86_64-linux-gnu-gcc-ar-12
/usr/bin/x86_64-linux-gnu-gcc-nm-11
/usr/bin/x86_64-linux-gnu-gcc-nm-12
/usr/bin/x86_64-linux-gnu-gcc-ranlib-11
/usr/bin/x86_64-linux-gnu-gcc-ranlib-12
/usr/bin/x86_64-linux-gnu-gcov-11
/usr/bin/x86_64-linux-gnu-gcov-12
/usr/bin/x86_64-linux-gnu-gcov-dump-11
/usr/bin/x86_64-linux-gnu-gcov-dump-12
/usr/bin/x86_64-linux-gnu-gcov-tool-11
/usr/bin/x86_64-linux-gnu-gcov-tool-12
/usr/bin/x86_64-linux-gnu-gprof
/usr/bin/x86_64-linux-gnu-ld.bfd
/usr/bin/x86_64-linux-gnu-ld.gold
/usr/bin/x86_64-linux-gnu-lto-dump-11
/usr/bin/x86_64-linux-gnu-lto-dump-12
/usr/bin/x86_64-linux-gnu-nm
/usr/bin/x86_64-linux-gnu-objcopy
/usr/bin/x86_64-linux-gnu-objdump
/usr/bin/x86_64-linux-gnu-ranlib
/usr/bin/x86_64-linux-gnu-readelf
/usr/bin/x86_64-linux-gnu-size
/usr/bin/x86_64-linux-gnu-strings
/usr/bin/x86_64-linux-gnu-strip
/usr/bin/x86_64-pc-linux-gnu-pkg-config
/usr/bin/xargs
/usr/bin/xauth
/usr/bin/xbiff
/usr/bin/xbrlapi
/usr/bin/xcalc
/usr/bin/xclip
/usr/bin/xclipboard
/usr/bin/xclock
/usr/bin/xcmsdb
/usr/bin/xconsole
/usr/bin/xcursorgen
/usr/bin/xcutsel
/usr/bin/xdg-dbus-proxy
/usr/bin/xdg-user-dirs-gtk-update
/usr/bin/xdg-user-dirs-update
/usr/bin/xditview
/usr/bin/xdpyinfo
/usr/bin/xdriinfo
/usr/bin/xedit
/usr/bin/Xephyr
/usr/bin/xev
/usr/bin/xeyes
/usr/bin/xfd
/usr/bin/xfontsel
/usr/bin/xgamma
/usr/bin/xgc
/usr/bin/xhost
/usr/bin/xinit
/usr/bin/xinput
/usr/bin/xkbbell
/usr/bin/xkbcomp
/usr/bin/xkbevd
/usr/bin/xkbprint
/usr/bin/xkbvleds
/usr/bin/xkbwatch
/usr/bin/xkill
/usr/bin/xload
/usr/bin/xlogo
/usr/bin/xlsatoms
/usr/bin/xlsclients
/usr/bin/xlsfonts
/usr/bin/xmag
/usr/bin/xman
/usr/bin/xmessage
/usr/bin/xml2ag
/usr/bin/xmlcatalog
/usr/bin/xmllint
/usr/bin/xmodmap
/usr/bin/xmore
/usr/bin/xorriso
/usr/bin/xprintidle
/usr/bin/xprop
/usr/bin/xrandr
/usr/bin/xrdb
/usr/bin/xrefresh
/usr/bin/xsel
/usr/bin/xset
/usr/bin/xsetmode
/usr/bin/xsetpointer
/usr/bin/xsetroot
/usr/bin/xsetwacom
/usr/bin/xsm
/usr/bin/xstdcmap
/usr/bin/xterm
/usr/bin/xvidtune
/usr/bin/xvinfo
/usr/bin/Xwayland
/usr/bin/xwd
/usr/bin/xwininfo
/usr/bin/xwud
/usr/bin/xxd
/usr/bin/xz
/usr/bin/yelp
/usr/bin/yes
/usr/bin/zdump
/usr/bin/zenity
/usr/bin/zip
/usr/bin/zipcloak
/usr/bin/zipinfo
/usr/bin/zipnote
/usr/bin/zipsplit
/usr/bin/zsh
/usr/bin/zstd
